### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by davidmorris178** [adnanafzal565/spa-chat-app-mevn#1]
Hi. I am a beginner of MEVN stack.
I installed this project and it outputs too many CORS error like this.

1. Access to XMLHttpRequest at 'http://localhost:3000/socket.io/?EIO=4&transport=polling&t=OQVvswa' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
2. GET http://localhost:3000/socket.io/?EIO=4&transport=polling&t=OQVvswa net::ERR_FAILED 200 (OK)

I googled for a long time and tried a lot but all failed.
What do I need to solve this issue?

**Comment by adnanafzal565** [comment]
Sorry for the late reply. 

You can follow this 33 second video tutorial to fix it:

https://www.youtube.com/watch?v=lVdi24uVs5k
